variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: dpsim-dev
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - docs

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    - docker images
  tags:
    - shell

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - build
  tags:
    - docker

docs:
  stage: docs
  script:
    - cd build
    - cmake ..
    - make docs
    - make docs_cxx
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - build/Documentation/html
      - build/Documentation/Cxx/html
  tags:
    - docker
