variables:
  DOCKER_IMAGE: dpsim-dev-${CI_COMMIT_REF_NAME}
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - test

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE} .
  tags:
    - shell

build:
  stage: build
  script:
    - mkdir Source/build
    - cd Source/build
    - cmake ..
    - make
  image: ${DOCKER_IMAGE}
  artifacts:
    paths:
      - Source/build
  tags:
    - docker

# remove tests again for now; they will be added back later when they can be
# done purely with python scripts using the new module
