variables:
  DOCKER_IMAGE: dpsim-dev-${CI_COMMIT_REF_NAME}

stages:
  - prepare
  - build
  - test

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE} .
  tags:
    - shell

build:
  stage: build
  script:
    - make -C Source
  image: ${DOCKER_IMAGE}
  tags:
    - docker

test:
  stage: test
  script:
    - make -C Source tests
    - cd Source/Tests
    - python3 run_tests.py
  image: ${DOCKER_IMAGE}
