variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  RSYNC_OPTS: --recursive --ignore-missing-args --chown ${DEPLOY_USER}:${DEPLOY_USER}
  DOCKER_IMAGE_DEV: dpsim-dev

before_script:
  - git config --local core.longpaths true
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - prepare
  - pre-build
  - build
  - test
  - deploy
  #- post-all

docker:
  stage: prepare
  script:
    - docker build -f Packaging/Docker/Dockerfile.dev -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    - docker images
  tags:
    - shell

build:linux:
  stage: pre-build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 8
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - build
  tags:
    - docker

build:docs:
  stage: build
  script:
    - make -C build docs
    - make -C build docs_cxx
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  dependencies:
    - build:linux
  artifacts:
    paths:
      - build/Documentation/html
      - build/Documentation/Cxx/html
  tags:
    - docker

build:packages:
  stage: build
  script:
    - make -C build package
  only:
    - tags
  tags:
    - docker
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  dependencies:
    - build:linux
  artifacts:
    paths:
      - build/*.rpm
      - build/*.tar.gz

build:docker:
  stage: build
  script:
    - docker build -f Packaging/Docker/Dockerfile -t rwthacs/dpsim:${DOCKER_TAG_DEV} .
  tags:
    - shell

test:pytest:
  stage: test
  script:
    - make -C build install
    - pytest -v
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  dependencies:
    - build:linux
  artifacts:
    paths:
      - Logs/
  tags:
    - docker

deploy:docker:
  stage: deploy
  script:
    - docker push rwthacs/dpsim:${DOCKER_TAG_DEV} .
  dependencies:
    - build:docker
  tags:
    - shell

deploy:docs:
  stage: deploy
  script:
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} mkdir -p ${DEPLOY_PATH}/doc/${CI_BUILD_REF_NAME}/{sphinx,doxygen}
    - rsync ${RSYNC_OPTS} --delete build/Documentation/html/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/doc/${CI_BUILD_REF_NAME}/sphinx
    - rsync ${RSYNC_OPTS} --delete build/Documentation/Cxx/html/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/doc/${CI_BUILD_REF_NAME}/doxygen
  dependencies:
    - build:docs
  only:
    - tags
    - master
    - development
  tags:
    - fein-deploy
  tags:
    - shell

deploy:packages:
  stage: deploy
  script:
    - rsync ${RSYNC_OPTS} build/*.rpm ${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/packages/redhat/x86_64
    - rsync ${RSYNC_OPTS} build/*.tar.gz ${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/dpsim/src
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} createrepo /var/www/packages/redhat
  dependencies:
    - build:packages
  only:
    - tags
  tags:
    - fein-deploy
  tags:
    - shell

# We run the windows build at last as it takes ages to finish
#build:windows:
#  stage: post-all
#  script:
#    - rmdir build /s
#    - mkdir build
#    - cd build
#    - cmake -G "Visual Studio 15 2017 Win64" ..
#    - cmake --build .
#  tags:
#    - windows