variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  RSYNC_OPTS: --recursive --ignore-missing-args --chown ${DEPLOY_USER}:${DEPLOY_USER}
  DOCKER_IMAGE_DEV: dpsim-dev
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - test
  - deploy

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    - docker images
  tags:
    - shell

build:code:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 8
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - build
  tags:
    - docker

build:docs:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make docs
    - make docs_cxx
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - build/Documentation/html
      - build/Documentation/Cxx/html
  tags:
    - docker

build:packages:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make package
  only:
    - development
    - master
    - tags
  tags:
    - docker
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - build/*.rpm
      - build/*.tar.gz

test:python:
  stage: test
  script:
    - make -C build install
    - python3 Examples/Python/ci.py
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  dependencies:
    - build:code
  artifacts:
    paths:
      - Examples/Python/*.csv
  tags:
    - docker

deploy:docs:
  stage: deploy
  script:
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} mkdir -p ${DEPLOY_PATH}/doc/${CI_BUILD_REF_NAME}/{sphinx,doxygen}
    - rsync ${RSYNC_OPTS} build/Documentation/html/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/doc/$CI_BUILD_REF_NAME/sphinx
    - rsync ${RSYNC_OPTS} build/Documentation/Cxx/html/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/doc/$CI_BUILD_REF_NAME/doxygen
  dependencies:
    - build:docs
  only:
    - tags
    - master
    - development
  tags:
    - fein-deploy
  tags:
    - shell

deploy:packages:
  stage: deploy
  script:
    - rsync ${RSYNC_OPTS} build/*.rpm ${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/packages/redhat/x86_64
    - rsync ${RSYNC_OPTS} build/*.tar.gz ${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/dpsim/src
    - ssh ${DEPLOY_USER}@${DEPLOY_HOST} createrepo /var/www/packages/redhat
  dependencies:
    - build:packages
  only:
    - tags
    - master
    - development
  tags:
    - fein-deploy
  tags:
    - shell

