variables:
  DOCKER_IMAGE: dpsim-dev-${CI_COMMIT_REF_NAME}
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - test

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE} .
  tags:
    - shell

build:
  stage: build
  script:
    - mkdir Source/build
    - cd Source/build
    - cmake ..
    - make
  image: ${DOCKER_IMAGE}
  artifacts:
    paths:
      - Source/build
  tags:
    - docker

test:
  stage: test
  script:
    - cd Source/Tests
    - python3 run_tests.py
  image: ${DOCKER_IMAGE}
  tags:
    - docker
