variables:
  PREFIX: /usr/
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - test

before_script:
  - git submodule foreach git checkout .

docker:
  stage: prepare
  script:
    - docker build -t dpsim-dev .
  tags:
    - shell

build:
  stage: build
  script:
    - make -C Source/VILLASnode install-libvillas-ext
    - make -C Source
  image: dpsim-dev
  tags:
    - docker

test:
  stage: test
  script:
    - make -C Source test
    - cd Source/Tests
    - python run_tests.py
  image: dpsim-dev
