variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: dpsim-dev
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build
  - docs
  - test

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
  tags:
    - shell

build:
  stage: build
  script:
    - mkdir Source/build
    - cd Source/build
    - cmake ..
    - make
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - Source/build
  tags:
    - docker

docs:
  stage: docs
  script:
    - make docs
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - Documentation/html
  tags:
    - docker

test:
  stage: test
  variables:
    PYTHONPATH: Source/build
  script:
    - python3 Examples/Python/ci.py
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker
