variables:
  DOCKER_IMAGE: dpsim-dev-${CI_COMMIT_REF_NAME}
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE} .
  tags:
    - shell

build:
  stage: build
  script:
    - mkdir Source/build
    - cd Source/build
    - cmake .. -DEigen3_DIR=/usr/share/eigen3
    - make
  image: ${DOCKER_IMAGE}
  tags:
    - docker

# no testing for now
