image: docker:latest

variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: dpsim-dev
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
# When using dind, it's wise to use the overlayfs driver for
# improved performance.

services:
- docker:dind

stages:
  - prepare
  - build
  - docs
  - test

docker:
  stage: prepare
  before_script:
    - docker info
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
  tags:
    - docker

build:
  stage: build
  script:
    - mkdir Source/build
    - cd Source/build
    - cmake ..
    - make
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - Source/build
  tags:
    - docker

docs:
  stage: docs
  script:
    - make docs
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  artifacts:
    paths:
      - Documentation/html
  tags:
    - docker

test:
  stage: test
  variables:
    PYTHONPATH: Source/build
  script:
    - python3 Examples/Python/ci.py
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker
